export { hasIosStaffbaseRuntime } from './hasIosStaffbaseRuntime'
export { isIOSTouchDevice } from './isIOSTouchDevice'
export { isMobile } from './isMobile'
export { isMobileOrWebview } from './isMobileOrWebview'
export { isMobilePlatform } from './isMobilePlatform'
export { isMobileViewport } from './isMobileViewport'
export { isNativeApp } from './isNativeApp'
