export type { FetchArticlesOptions } from '../types/news/FetchArticlesOptions'
export type { NewsApi } from '../types/news/NewsApi'
export type { NewsApiConfig } from '../types/news/NewsApiConfig'
export { acknowledgeArticle } from './acknowledgeArticle'
export { channelToOption } from './channelToOption'
export { createNewsApi } from './createNewsApi'
export { fetchArticleById } from './fetchArticleById'
export { fetchArticles } from './fetchArticles'
export { fetchChannel } from './fetchChannel'
export { fetchChannels } from './fetchChannels'
export { fetchSpaceName } from './fetchSpaceName'
export { isArticlePublished } from './isArticlePublished'
export { keepPublishedArticle } from './keepPublishedArticle'
